<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260713131547 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE hospitalization (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ward VARCHAR(255) NOT NULL, room VARCHAR(20) NOT NULL, admission_date DATE NOT NULL, discharge_date DATE DEFAULT NULL, status VARCHAR(20) NOT NULL, reason TEXT DEFAULT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, patient_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_40CF08916B899279 ON hospitalization (patient_id)');
        $this->addSql('ALTER TABLE hospitalization ADD CONSTRAINT FK_40CF08916B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE hospitalization DROP CONSTRAINT FK_40CF08916B899279');
        $this->addSql('DROP TABLE hospitalization');
    }
}
